// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nerdvault/Discover.tsx": () => import("../components/mockups/nerdvault/Discover.tsx"),
  "./components/mockups/nerdvault/Friends.tsx": () => import("../components/mockups/nerdvault/Friends.tsx"),
  "./components/mockups/nerdvault/Home.tsx": () => import("../components/mockups/nerdvault/Home.tsx"),
  "./components/mockups/nerdvault/MediaDetail.tsx": () => import("../components/mockups/nerdvault/MediaDetail.tsx"),
  "./components/mockups/nerdvault/Profile.tsx": () => import("../components/mockups/nerdvault/Profile.tsx"),
  "./components/mockups/nerdvault/Vault.tsx": () => import("../components/mockups/nerdvault/Vault.tsx")
};
